-- SMS inbox table for auto-fetch pipeline
-- Run this in Supabase SQL Editor

create table if not exists public.sms_inbox (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    sender text,
    message text not null,
    received_at timestamptz,
    processed boolean not null default false,
    parse_status text,
    processed_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists idx_sms_inbox_user_processed_created
    on public.sms_inbox (user_id, processed, created_at desc);

alter table public.sms_inbox enable row level security;

drop policy if exists "sms_inbox_select_own" on public.sms_inbox;
create policy "sms_inbox_select_own"
on public.sms_inbox
for select
using (auth.uid() = user_id);

drop policy if exists "sms_inbox_update_own" on public.sms_inbox;
create policy "sms_inbox_update_own"
on public.sms_inbox
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "sms_inbox_insert_own" on public.sms_inbox;
create policy "sms_inbox_insert_own"
on public.sms_inbox
for insert
with check (auth.uid() = user_id);
